# Generated by Django 5.1.2 on 2024-10-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='active', default=False)),
                ('created_at', models.DateField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(db_column='name', max_length=70)),
                ('cpf', models.CharField(db_column='cpf', max_length=12)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=11)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='active', default=False)),
                ('created_at', models.DateField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateField(auto_now=True, db_column='updated_at')),
                ('price_hour', models.FloatField(db_column='price_hour')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='active', default=False)),
                ('created_at', models.DateField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateField(auto_now=True, db_column='updated_at')),
                ('license_plate', models.CharField(db_column='license_plate', max_length=10)),
                ('car_model', models.CharField(db_column='car_model', max_length=10)),
                ('colour', models.CharField(db_column='colour', max_length=10)),
                ('vehicle_type', models.CharField(db_column='vehicle_type', max_length=10)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='parking.client')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='active', default=False)),
                ('created_at', models.DateField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateField(auto_now=True, db_column='updated_at')),
                ('check_in', models.DateTimeField(auto_now_add=True, db_column='check_in')),
                ('check_out', models.DateTimeField(auto_now=True, db_column='check_out')),
                ('total_value', models.FloatField(db_column='total_value', default=0.0)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='parking.client')),
                ('id_parking_spot', models.ForeignKey(db_column='id_parking_spot', on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspot')),
                ('id_vehicle', models.ForeignKey(db_column='id_vehicle', on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='id_vehicle',
            field=models.ForeignKey(db_column='id_vehicle', on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle'),
        ),
    ]
