# Generated by Django 5.1.1 on 2024-10-05 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),
    ]